on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  push:
    branches: main
    tags: 
      - v1.**
  release:
    types: [created]
  schedule:
    - cron: '30 5,17 * * *'
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "hello world"
